name: debris-landlab
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - pyyaml
  - rasterio
  - requests
  - fiona
  - geopandas
  - shapely
  - pyproj
  - zarr
  - landlab
  - bmi-topography
  - matplotlib
